### ISSUE TITLE
Incompatibility with Thorium

### ISSUE THREAD

**Issue by LeeroyGarfield** [BlanketMC/blanket-client-tweaks#29]
**Describe the bug**
When Blanket and [Thorium](https://www.curseforge.com/minecraft/mc-mods/thorium), a mod containing a collection of bugfixes, are installed together, the launcher crashes before the game window even appears.

**To Reproduce**
1. Download and install [Thorium](https://www.curseforge.com/minecraft/mc-mods/thorium/files/3692154)
2. Install Blanket
3. Start the game through the launcher

**Expected behavior**
Crashes in the middle of the launching process.

**Desktop (please complete the following information):**
 - Minecraft 1.18.2
 - Fabric API 0.48.0
 - Blanket 1.0.1
 - Thorium 1.0.0

**Minecraft crash report**
```
[main/ERROR]: Mixin apply for mod thorium failed thorium.mixins.json:server.WolfEntityMixin -> net.minecraft.class_1493: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1493::fixedGetTailAngleWhenNotAngry with priority 1000 cannot inject into net/minecraft/class_1493::method_6714()F merged by io.github.blanketmc.blanket.mixin.fixes.WolfEntity_tailSpinMixin with priority 1000 [PREINJECT Applicator Phase -> thorium.mixins.json:server.WolfEntityMixin -> Prepare Injections ->  -> handler$zji000$fixedGetTailAngleWhenNotAngry(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1493::fixedGetTailAngleWhenNotAngry with priority 1000 cannot inject into net/minecraft/class_1493::method_6714()F merged by io.github.blanketmc.blanket.mixin.fixes.WolfEntity_tailSpinMixin with priority 1000 [PREINJECT Applicator Phase -> thorium.mixins.json:server.WolfEntityMixin -> Prepare Injections ->  -> handler$zji000$fixedGetTailAngleWhenNotAngry(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) [client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[21:41:42] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1493 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1493 failed
	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1493 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [thorium.mixins.json:server.WolfEntityMixin] from phase [DEFAULT] in config [thorium.mixins.json] from mod [thorium] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1493::fixedGetTailAngleWhenNotAngry with priority 1000 cannot inject into net/minecraft/class_1493::method_6714()F merged by io.github.blanketmc.blanket.mixin.fixes.WolfEntity_tailSpinMixin with priority 1000 [PREINJECT Applicator Phase -> thorium.mixins.json:server.WolfEntityMixin -> Prepare Injections ->  -> handler$zji000$fixedGetTailAngleWhenNotAngry(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 10 more
```

**Additional context**
I only installed Fabric API, Blanket and Thorium through MultiMC.

**Comment by KosmX** [comment]
https://github.com/BlanketMC/blanket-client-tweaks/blob/2fb6453cb34b8df343baa50f3df8995b25dac5f9/src/main/java/io/github/blanketmc/blanket/mixin/fixes/WolfEntity_tailSpinMixin.java#L24

Blanket should not override that function

**Comment by KosmX** [comment]
With the inject, if both Thorium and Blanket is loaded, the method will look like this
```java
    public float method_6714() {
        if (this.method_29511()) {
            return 1.5393804F;
        } else {
            CallbackInfoReturnable callbackInfo2 = new CallbackInfoReturnable("method_6714", true);
            this.handler$zjk000$fixedGetTailAngleWhenNotAngry(callbackInfo2);
            if (callbackInfo2.isCancelled()) {
                return callbackInfo2.getReturnValueF();
            } else if (this.method_6181()) {
                float callbackInfo1;
                float var10000 = callbackInfo1 = (0.55F - (this.method_6063() - this.method_6032()) * 0.02F) * 3.1415927F;
                CallbackInfoReturnable callbackInfo1 = new CallbackInfoReturnable("method_6714", true, callbackInfo1);
                this.handler$zzi000$getTailAngle(callbackInfo1);
                return callbackInfo1.isCancelled() ? callbackInfo1.getReturnValueF() : var10000;
            } else {
                return 0.62831855F;
            }
        }
    }
```

**Comment by KosmX** [comment]
1.0.2 has been released with the fix.
https://modrinth.com/mod/blanket/version/1.0.2
