### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by mdxd44** [BlanketMC/blanket-client-tweaks#44]
**Describe the bug**
Crash while launching.

**To Reproduce**
1. Launch game.

**Expected behavior**
No crash i guess.

**Desktop (please complete the following information):**
 - Minecraft version: 1.20.1
 - Mod version: https://github.com/BlanketMC/blanket-client-tweaks/actions/runs/5315685794

**Minecraft crash report**
```
java.lang.RuntimeException: Mixin transformation of com.mojang.authlib.yggdrasil.YggdrasilUserApiService failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:143)
	at net.minecraft.class_310.method_31382(class_310.java:733)
	at net.minecraft.class_310.<init>(class_310.java:442)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [blanket-client-tweaks.mixins.json:fixes.YggdrasilUserApiService_syncBlockListMixin from mod blanket-client-tweaks] from phase [DEFAULT] in config [blanket-client-tweaks.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method fetchBlockList in blanket-client-tweaks.mixins.json:fixes.YggdrasilUserApiService_syncBlockListMixin from mod blanket-client-tweaks was not located in the target class com.mojang.authlib.yggdrasil.YggdrasilUserApiService. Using refmap Blanket Client tweaks-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more
```

**Comment by KosmX** [comment]
Can you share full game logs?

**Comment by mdxd44** [comment]
What will the full report give you? According to the trace it is quite obvious that in the mixin YggdrasilUserApiService_syncBlockListMixin will be enough to update the field name.
[crash-2023-08-07_21.31.55-client.txt](https://github.com/BlanketMC/blanket-client-tweaks/files/12316800/crash-2023-08-07_21.31.55-client.txt)

**Comment by KosmX** [comment]
The reason I requested a full log is because it works on my machine. Something is wrong with your setup: your MC authentication appears to be modified.



Please try this one and create a file `blanket-client.mixin.properties` with this:
```
YggdrasilUserApiService_syncBlockListMixin = false
```
[blanket.zip](https://github.com/BlanketMC/blanket-client-tweaks/files/12317839/blanket.zip)

This should disable the affected mixin.

> I'll commit the code tomorrow.

**Comment by mdxd44** [comment]
Without this mixin client launches normally, my launcher uses custom authlib.
[authlib-4.0.42.1.zip](https://github.com/BlanketMC/blanket-client-tweaks/files/12328444/authlib-4.0.42.1.zip)

**Comment by KosmX** [comment]
Great!
Please use the mixin disable function. There is no reason to patch your already patched authlib.
